### ISSUE TITLE
Newsflash box is cerise, not green

### ISSUE THREAD

**Issue by danielsson** [datasektionen/gloo-bawang#2]
Expected:
<img width="795" alt="screen shot 2016-06-10 at 14 34 19" src="https://cloud.githubusercontent.com/assets/139248/15956059/72c19cd2-2f18-11e6-919f-91dbbd99a163.png">

Actual:
<img width="1210" alt="screen shot 2016-06-10 at 14 26 20" src="https://cloud.githubusercontent.com/assets/139248/15956046/59e54470-2f18-11e6-84b8-4b9cf4bf9297.png">

**Comment by danielsson** [comment]
hahahah

**Comment by mheine** [comment]
Mattias pls
